apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitopsreact-es-cluster
  namespace: gitopsreact-es
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NETWORK_HOST
              value: 'site,local'
            - name: discovery.zen.ping.unicast.hosts
              value: 'gitopsreact-es-cluster-0.elasticsearch.gitopsreact-es.svc.cluster.local,gitopsreact-es-cluster-1.elasticsearch.gitopsreact-es.svc.cluster.local,gitopsreact-es-cluster-2.elasticsearch.gitopsreact-es.svc.cluster.local'
            - name: ES_JAVA_OPTS
              value: '-Xms1g -Xmx1g'
      initContainers:
        - name: fix-permissions
          image: busybox
          command:
            ['sh', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
        - name: increase-vm-max-map
          image: busybox
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command: ['sh', '-c', 'ulimit -n 65536']
          securityContext:
            privileged: true
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: elasticsearch
      spec:
        accessModes: ['ReadWriteOnce']
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 2Gi
