apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: darylwalsh/gorapi:0.1.0
          ports:
            - containerPort: 8080
              name: api
            - containerPort: 8100
              name: docs
          env:
            - name: ELASTICSEARCH_HOSTNAME
              value: 'elasticsearch'
            - name: ELASTICSEARCH_PORT
              value: '9200'
            - name: CLIENT_PROTOCOL
              value: 'http'
            - name: CLIENT_HOSTNAME
              value: 'localhost'
            - name: CLIENT_PORT
              value: '8200'
            - name: SERVER_PROTOCOL
              value: 'http'
            - name: SERVER_HOSTNAME
              value: 'localhost'
            - name: SERVER_PORT
              value: '8080'
            - name: SERVER_EXTERNAL_PROTOCOL
              value: 'http'
            - name: SERVER_EXTERNAL_HOSTNAME
              value: 'api.gitopsreact.com'
            - name: SERVER_EXTERNAL_PORT
              value: '80'
            - name: ELASTICSEARCH_PROTOCOL
              value: 'http'
            - name: ELASTICSEARCH_INDEX
              value: 'gitopsreact'
            - name: SWAGGER_UI_PROTOCOL
              value: 'http'
            - name: SWAGGER_UI_HOSTNAME
              value: '127.0.0.1'
            - name: SWAGGER_UI_PORT
              value: '8000'
            - name: PUBLIC_KEY
              value: '-----BEGIN RSA PUBLIC KEY-----/nMIICCgKCAgEA2QA6RrI9qNh3DoJsYSlfzGytCu35GSXcGnjLtXvnLGO6PcqrVySa/n09XltZTOaxfjWQvulzq+qp0XXXMzev7rewm1C8eypJFfSN6et/b4+mQ/0CMCFLZr/nXCB8JOJu6yqRCWSNeGXWbWMvVI3+JYl137kGAil9kPfVW1Pb7FmhxKDo0TafUrYm/nAYkL8fRG4EXoOmNpgHmUQWg5rP0OnS7PvbziRUd8VxvIO8+nKIap1ELFbTayFq0X/nF1IWuHO+JvUqrBDiYfpAxy2lYF1/bJRfqNS1dqRyq7J4bwzR/gieOnq+MaIWO7NO/nRCtRdwbVyBUZxKrTlIWQ7xN0mkVcbtiKSAL+4VeBg3b85nPz2wsm0YVCe63QTltC/nzAn08ZBb/RLuzZO9Lk/U5/QA2GKVugWRAbXo93M0UrArD1Ws4YEU9x2tjpray0CM/nel0Ms4hnQwRUSejwSYDaCLAIMUxrhcfG46A0BNZiWDEHATGwOg0XKdDyOWfrP5JD/n76cTfbgt4JrzgaWK0CRj258C3Q75afoKLz+VUoTpOU1CpQFdf+/y3mVzY+cfMuTE/n3UaWKvgZWQ0PZ/clrLwOVbBcCHIIsUwjwZWgaHeYJj1KDNbQ7sFMkiNN6COi2JxN/nOBCBGhi62u5paFHf+FounJa+6KLiYZaflKEZFZM0bQG2S50K+15lUgUCAwEAAQ==/n-----END RSA PUBLIC KEY-----'
            - name: PRIVATE_KEY
              value: '-----BEGIN RSA PRIVATE KEY-----/nMIIJKQIBAAKCAgEA2QA6RrI9qNh3DoJsYSlfzGytCu35GSXcGnjLtXvnLGO6Pcqr/nVySa09XltZTOaxfjWQvulzq+qp0XXXMzev7rewm1C8eypJFfSN6et/b4+mQ/0CMC/n FLZrXCB8JOJu6yqRCWSNeGXWbWMvVI3+JYl137kGAil9kPfVW1Pb7FmhxKDo0Taf/n UrYmAYkL8fRG4EXoOmNpgHmUQWg5rP0OnS7PvbziRUd8VxvIO8+nKIap1ELFbTay/n Fq0XF1IWuHO+JvUqrBDiYfpAxy2lYF1/bJRfqNS1dqRyq7J4bwzR/gieOnq+MaIW/n O7NORCtRdwbVyBUZxKrTlIWQ7xN0mkVcbtiKSAL+4VeBg3b85nPz2wsm0YVCe63Q/n TltCzAn08ZBb/RLuzZO9Lk/U5/QA2GKVugWRAbXo93M0UrArD1Ws4YEU9x2tjpra/n y0CMel0Ms4hnQwRUSejwSYDaCLAIMUxrhcfG46A0BNZiWDEHATGwOg0XKdDyOWfr/n P5JD76cTfbgt4JrzgaWK0CRj258C3Q75afoKLz+VUoTpOU1CpQFdf+/y3mVzY+cf/n MuTE3UaWKvgZWQ0PZ/clrLwOVbBcCHIIsUwjwZWgaHeYJj1KDNbQ7sFMkiNN6COi/n 2JxNOBCBGhi62u5paFHf+FounJa+6KLiYZaflKEZFZM0bQG2S50K+15lUgUCAwEA/n AQKCAgBID1ZK0be+ERwAGnlpDnc8iD4yafIVUsgzljd3bczHpdpb2KhrSMGNZPNi/n CCc/0u/xSxAQ8jYMrBvtMWtABdUmx4NyhP8ivQ+aQCsOxhnJ9G5obKetPyKJtlPj/n X7obp8gACX8dIxxAuPYnqvthdbNJ9sQzBZooANS9/iwC4YThqdmGWBAyREB8tAje/n cRL0OOK0OPz45+a+jaDRfDtVIQ1lYYr2HJYCyzwD+KH2yDkvPnkXGlmrRBFt8hmP/n aQgVIcbo2raCeLr4KYVIaeP9p4vYocIcwuE9eQebQPOe2zfIDaiJDN07OADejFAC/n KafmSHOFJoEaSfxmF9zZufzG5muMf7BrvUG7u84GIJiTURoJ9EzIawNTPcXx99xW/n hCdZhXVeRAGHTM3BI7hry51uJeahDVi9DHMAkvXS+6TcobRCow+pyM6bS8cq+Kjf/n JA1T4LC7lsaFoT1i895vsFSBk34Ccd17Tq4xcVv5r+QrLRrmFDdg7R09FK4XG+yg/n Vuu2bufcSuJrUATpQQ1HJ0N7z4lm+RKAi8n6RPNQMSQumbWtT4tJX9Tb6iEkgV5T/n kpTJd+t4cuo7DEvhgxHqivqWWE5kG3s6rf3pkXPutIpEb6EpDw2rOZtt6l9KHwej/n fsmwFfzOhP/E2GWsneT/aNEFerFRzXhd+QTkJA+UzXnKJesrgQKCAQEA8nU4CPLx/n byHmhAl1/MMpgnWRjb10fbhRVcgO8bu6zpYxLKF3/RRuvp/0OOjSt2dP+eiNiK/u/n JFry0VIhC5LI32Fp1LsHGqGGUa9CKRXRtuh3ckYaFi6IIfHy9Yj1zUqtDBMV0RHU/n iwAV2R7kkfcdiNz9FwlGgF++VdKjSWLRH6+URNQIMgx8b/kWjTI+CmAVbVj2V+S0/n Isn/huZGjlyb8+u/FgdfKrMzl/HJ61CZ9F/yV5P+GhbndQ5P92QL8gxe4thRMU68/n wl8QmOz2BH01UN7jtxhKw+zsoL9izwMe/y7xjol/izqE6OKZ7TtT9sou1wnbrQsz/n 6z8mvBHqvniS5QKCAQEA5R8DHy5xT6wEz8JCmBt3MK34HS7VGaXp8xesBXjkQjfj/n qLymr6r1nv4cTrz8iKbLlAJ0s1wFhj6LPMcoOe4FRMyEGK9AR4f+UMrmlKJ6s29r/n GGfoQLj6+3GWzO/hG8SRlE5TTJTGI4W/k7zbRWP6RVw8ZHpiieV3LZ1CzNmngBWy/n LVwY3Bg8cqJmJi7iyAU2MzF7067BPaZnMwMpLEX87sy3tPb8zbx3k8PzsIusBSjN/n mEqfLno2/idvs71YNftWZUtRZ7XidYxNacppJZOoJnjrJFHon47b4irTIEw4lHc2/n 20KwL+MPM/ndUM10yjroPo8e+ATchkzhgs1tpo4woQKCAQEA19uqbrU0Y/evjgAK/n TmXGkAJx+togW0l9CD0bqPW1A/XNg+mhtOy7B/XKbdxCtcxB9MGpOHdBMpbSNa/E/n AdTGB7JnkWCNm5UQy6qX4ZIuaoSey1tEIFl/E5Gf+B/ejs4cMHLRaphQPQxvZyVM/n 4/M5FT+CCD9WyDX1c90bSNu0SVx9SaXoQf7BzsLZ5A1GFOCkUvzwHSJdideDKqvb/n RyWGJuzM7CTWAmMW3QED/v98gYfmbzgv8zRPDvUWFq+4vt9qntVtu9NY1Efks/HL/n ugVrMTuvSrRS5AoMRbT+mEU0FIbLwlYB+oe4Csqrtfyq7T3l48dAD9i4eYl4x9m//n v6IDTQKCAQAMeG6kENQMARHV+P3E56HKHX3moLjqh3Q/TeeH+Ld7vyz97x6nawep/n Wq1Rv8mC6okkCiot5PFMCDVt3m0bEhBpWTRLX6aA/i7iWNjJ+DnzcDoE/wrOEwNe/n EiWiC+BVsZI23zh7b5GFN29g7COHGFTz13xV/69DUCD3c5rCKYqLVyL2gw+7Uvpf/n RuWGaIDhYB8+FBBoShesclUlmqNwDHMi0DOjftntnLdpbH3j+wYm1byy8ETPs8kw/n dhcHUmPttDtUkg/hNC4aNcO04VZtvCanyWcK+AZQQOdI3QnWtS9TLVXoAy4xvQsD/n yjK4hiY4J5KibQnDeAhEqwSPKP0x1oVhAoIBAQCOthYLY1qdCz9yHAPRYKreofgq/n Kce/Y3bL0i/y9AqFZ6C2U0G3yLOFTPHOJaiZXMh07jpGumroxHKNLFNc92GbjOTG/n aPQSdpM+CwiKYk6fbyEtSfeN3XSbNuX3icAI2eyuJkEruukyTn3uC8HlOmh8exYQ/n vg91tSjOtI80+u9iXD5XL7W+GoONqxMTej0gcotLWIpsQTOPK8c20eAwqrFvISKT/n OWIDSXDTtC3oWejfoSFJg3tc4rvEFtCgzGy43omY4VnsX34VJgEMsS9xotDEbFxG/n BQrPUDibv65TrBchQwCDhLfihEQ5n38hUdbbn/J7Y45IpAl1HMkd6Nzn/tPj/n -----END RSA PRIVATE KEY-----'
