apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: darylwalsh/gorapi:0.1.0
          ports:
            - containerPort: 8080
              name: api
            - containerPort: 8100
              name: docs
          env:
            - name: ELASTICSEARCH_HOSTNAME
              value: 'elasticsearch'
            - name: ELASTICSEARCH_PORT
              value: '9200'
            - name: CLIENT_PROTOCOL
              value: 'http'
            - name: CLIENT_HOSTNAME
              value: 'localhost'
            - name: CLIENT_PORT
              value: '8200'
            - name: SERVER_PROTOCOL
              value: 'http'
            - name: SERVER_HOSTNAME
              value: 'localhost'
            - name: SERVER_PORT
              value: '8080'
            - name: SERVER_EXTERNAL_PROTOCOL
              value: 'http'
            - name: SERVER_EXTERNAL_HOSTNAME
              value: 'api.gitopsreact.com'
            - name: SERVER_EXTERNAL_PORT
              value: '80'
            - name: ELASTICSEARCH_PROTOCOL
              value: 'http'
            - name: ELASTICSEARCH_INDEX
              value: 'gitopsreact'
            - name: SWAGGER_UI_PROTOCOL
              value: 'http'
            - name: SWAGGER_UI_HOSTNAME
              value: '127.0.0.1'
            - name: SWAGGER_UI_PORT
              value: '8000'
            - name: PUBLIC_KEY
              value: ''
            - name: PRIVATE_KEY
              value: ''
